/** Human labels for API response keys. */
const KEY_LABELS: Record<string, string> = {
  searchType: 'Input type',
  searchValue: 'Input value',
  productSlug: 'Product',
  status: 'Status',
  message: 'Message',
  result_code: 'Result code',
  result: 'Response payload',
  providerRef: 'Provider reference',
  transaction_id: 'Transaction ID',
  url: 'Session / consent URL',
  report: 'Skip tracing report',
  report_url: 'Report',
  expires_on: 'Expires (ITR)',
  expires: 'Expires (Ecom)',
  detail: 'Error detail',
  creditsRemaining: 'Credits remaining',
  http_response_code: 'HTTP code',
  request_id: 'Request ID',
  client_ref_num: 'Client reference',
  pan: 'PAN',
  pan_type: 'PAN type',
  fullname: 'Full name',
  full_name: 'Full name',
  first_name: 'First name',
  middle_name: 'Middle name',
  last_name: 'Last name',
  gender: 'Gender',
  aadhaar_number: 'Aadhaar',
  aadhaar_linked: 'Aadhaar linked',
  dob: 'Date of birth',
  pan_status: 'PAN status',
  pan_allotment_date: 'PAN allotment date',
  mobile: 'Mobile',
  mobile_number: 'Mobile',
  email: 'Email',
  is_salaried: 'Salaried',
  is_director: 'Director',
  is_sole_proprietor: 'Sole proprietor',
  signatory_details: 'Signatory details',
  address: 'Address',
  building_name: 'Building',
  locality: 'Locality',
  street_name: 'Street',
  pincode: 'PIN code',
  city: 'City',
  state: 'State',
  country: 'Country',
  gstin: 'GSTIN',
  reg_no: 'Registration number',
  registration_number: 'Registration number',
  rc_number: 'RC number',
  vehicle_number: 'Vehicle number',
  owner_name: 'Owner name',
  father_name: "Father's name",
  present_address: 'Present address',
  permanent_address: 'Permanent address',
  pan_number: 'PAN',
  id_number: 'ID number',
  masked_aadhaar: 'Masked Aadhaar',
  client_id: 'Client ID',
  bank_ifsc: 'Bank IFSC',
  bank_account_no: 'Bank account number',
  bank_details: 'Bank details',
  bank_account_number: 'Bank account number',
  ifsc: 'IFSC',
  vpa: 'UPI / VPA',
  uan: 'UAN',
  uan_number: 'UAN',
  uan_list: 'UAN list',
  uan_profile_data: 'UAN profile',
  gstin_data: 'GSTIN data',
  legal_name: 'Legal name',
  trade_name: 'Trade name',
  date_of_registration: 'Registration date',
  taxpayer_type: 'Taxpayer type',
  document_type: 'Document type',
  challan_details: 'Challan details',
  challan_number: 'Challan number',
  offense_details: 'Offense details',
  owner_history: 'Owner history',
  current_owner_name: 'Current owner',
  masked_name: 'Masked name',
  vehicle_category: 'Vehicle category',
  maker_model: 'Make / model',
  fuel_type: 'Fuel type',
  insurance_upto: 'Insurance valid until',
  pucc_upto: 'PUCC valid until',
  registration_date: 'Registration date',
  less_info: 'Limited info flag',
  category: 'Category',
  input_dob: 'Input DOB',
  dob_verified: 'DOB verified',
  phone_number: 'Phone',
  full_name_split: 'Name parts',
  prefill_details: 'Prefill details',
  pan_details: 'PAN details',
  personal_info: 'Personal info',
  phone_info: 'Phone numbers',
  address_info: 'Addresses',
  email_info: 'Email addresses',
  identity_info: 'Identity documents',
  personal_data: 'Personal data',
  personal_information: 'Personal information',
  alternate_phone: 'Alternate phones',
};

export function resultFieldLabel(key: string): string {
  if (KEY_LABELS[key]) return KEY_LABELS[key];
  return key
    .replace(/_/g, ' ')
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (s) => s.toUpperCase())
    .trim();
}
